server:
  port: 8080
spring:
  application:
    name: "cleanArchitecture"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://root:example@192.168.1.8:27017/clean-architecture?authSource=admin"
  datasource:
    url: "jdbc:postgresql://127.0.0.1:5232/clean-architecture"
    username: "postgres"
    password: "postgres"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
mongoConfig:
  user: "root"
  password: "example"
  connectionString: "mongodb://root:example@192.168.1.8:27017"
  database: "clean-architecture"
