version: "3.9"
services:
  postgresdb:
    image: postgres:14.4-alpine
    container_name: pgsql
    restart: always
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      # - $HOME/database:/var/lib/postgresql/data
    ports:
      - "5232:5432"
    expose:
      - "5232"
    environment:
      POSTGRES_DB: clean-architecture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SERVICE_NAME: postgresdb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge